{% set name = "ipdb" %}
{% set version = "0.11" %}
{% set sha256 = "7f3016284fb0f4859e9692ecfda18e4d703c5ffc7e493d899831a7db2c187a16" %}

{% set gh_org = "gotcha"  %}
{% set gh_repo = name %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{ gh_org }}/{{ gh_repo }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - ipdb = ipdb.__main__:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - ipython

test:
  imports:
    - ipdb

about:
  home: https://github.com/{{ gh_org }}/{{ gh_repo }}
  license: BSD-3
  summary: "Integration of IPython pdb"

extra:
  recipe-maintainers:
    - vamega
