travis:
  secure:
    BINSTAR_TOKEN: YU98BKa5NZ/7SMtToe9dF6mqA0XRuaq9qcg0xx/CYyjX3UujoEEHIb7HV9wwo0CDuBgHsbd12F7A7ovLziZApRN6r+jnLg3atKwbn9WbVmMM/JCJAVsYsEAPSRJAFN4diCeE5WcVrql4UbXz2dswbFrydhPCoei7+RygB39hXfv2mnbfL1xcA5saShUSkDSG00583vsm3oNUXYwfSbVN+5j9mTR1KGQP2BRZVL9aXOBSneMp531qPxGJkLtPHp8miigrId7bpapa37Qo4jKurpFddp2d+gGOdBDxR0pjokAvd9z9BZCckn556KQtheAIZFIdiyor04/u69FWt+AAmGK/sM7N6hTXemPELGBcUsMGNHC+5sMXm814uUoSEbThGtgzF59SwTMPNd3l95b1sGCYRrTBH+rpSAAcGJQ+5UXuvz4FzsujCaKM7Nyx0yi+DR76y0+8JdkcRxMlOeRAjtonOzl0rO3LuUYpPztmK+BqThFR3p484Qsg8dh7jLFahSCHlSS93cXi7JCJeB1CF8NOxm329wxWcoZDMfhUCWdMugjpfE9xLiR+6MjOszhzwAJ9Vi8OWejcFUhH8O36IYtRd2StY20WtaV3h36dMJWpMDTzp8i3SLjbcuKrKo+klqW7w/NeqSHJrcqCLg2qVdM71iEaMrIJuRltnIddAfM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
