travis:
  secure:
    BINSTAR_TOKEN: fnEg7+ZS9KdjlRJ5eZ4KFYbxv7tvMypVyvE5QozJcBlrD+a8cF9YddHETdFyLGBj6+4l/VsLKoCJf1Rzlfo1oDP4fECv8bKZsAwYPfNDuyzzOqjLrMzA/c5To1eE4z27qUFLnadh1ymdqX81PnQ3ORWhHgcLU4bRNV7sl0FcqdXYzpftg+2leF5ge56H1O161GRbRNkQIeWtUZnmIoOe+2f6K5GKnw1jzNZFBhlKzC6FQefCvJ4drJz9Y2rk9Ion5zzdZZRaD1XUGBH0D7Bou9hZxpyFAWLbNobovJRu0CeGOppD9MAleGlSbhokYmtDiU8MM5k2nbJt63hM/8wTHInbSr9COcBSrxf6vMlnGPfCv8icat9OHPwj45mxrE54nvjrXWt9kzb+2vpc7EW/6xMQjm3Dotjv5onpYl9lkykKxisREMCj7xLTUnzwa124zTy4vyFShDcVxAiKzT/Mt2U/95+KJFsF/pbKtJBZPuvpuDh/+aO3XWENjToVY/cKmAO/cBCinU+6BXZHoDsidBDfWp/oYHP+IxZn1wLPcKNfeOQRkC9vGXzlXUKfbOck2l/PM6nmuetecGHNL2l/w5QRiyVj4kURCRGQLtxUS2OM5WfRpcOP/QO9siEipz/CEOjT4IqG9HXGbjVRw/vFZiy427S749AmT4wnu84imGs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
