travis:
  secure:
    BINSTAR_TOKEN: Zxi/TAG+kDKz8XvoOzUuVF6AEfeDR0OCwFS2tdmX1Q2EEVHl8/ZolxogyQc7bxLvGWiVNzv91nYEQw3rY5zOQhzcG9Ifk01O0wYBiFMs7hwxb/k3Qkb/XSZ3/XIilqekde50bZib8fZkdIUancq9DWoyYUR6Es4c1Sgl0F7ntrauzIybKBJrOzmE7w7Kb31rp8DRFepdL5BU0LBuY3dfXIf0DZ9QQ7pQg152U4+4kxE5Ohez117p18RIvj/cQ8qwu4zbu3ZrdbVsrLXyEj2UovHbkORUXMfjoMDxQoGYEz1vBQUB5OzbUFv2zs5cw7nGxF6tZeXNZcLAHVTTL2vcEm62jAacnXieU5OsfGK8g55zqReMZUmN3eQl6fQaLPMvwdReycb8IAKtydTX/NeaOnuSsL6w2gQ1xs7zndmfTwwRIkXIAuozlH/GIH4DaXepz2sA5TOi0plySFTl+a2ZLJ4894tBEZzuebGQLuYHZTsz7qGgIq7OukMeqCWtqrWTYTUR9MfYnPT7KZUDBJ9azr5nCPLWd/Sz9L8ymq1ipTy801fYAKXA+YiydBEBNrf3zUvNrVcXqjFFci1EcNtP6C+GMTK6h4N3qLRI0bPdA/Hx/j+BpL2lezM2pILcvS69yNF/CiczvfLsTI1vI61ihfcB3ts7QIWwbBjU4VAm3h0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
